/*
    config.js

    Stores all constant definitions for player ships, enemies, upgrades, and abilities.
    Read-only values that are only tweaked for balance.
*/

//Streak names
const streakNames = [
    "Double Kill",
    "Triple Kill",
    "Quadra Kill",
    "Penta Kill",
    "Hexa Kill",
    "Hepta Kill",
    "Octo Kill",
    "Nona Kill",
    "Deca Kill",
    "Super Combo",
    "Hyper Combo",
    "Ultra Combo",
    "Mega Combo",
    "Giga Combo",
    "Tera Combo",
    "Peta Combo",
    "Exa Combo",
    "Zetta Combo",
    "Yotta Combo",
    "Bronto Combo",
    "Overkill",
    "Unstoppable",
    "Annhilating",
    "Godlike",
    "Ungodly",
];

//Information about each of the player's ship: health, armor, damage, shot count,...
const playerShips = [
    {
        id: 1,
        image: loadImage("images/player/player1.png"),
        frontShots: 1,
        sideShots: 0,
        bounceCount: 0,
        width: 64,
        height: 64,
        maxHealth: 100,
        maxArmor: 100,
        armorRegen: 10,
        movementSpeed: 3,
        originShootingCooldown: 20,
        projectileDamage: 20,
        projectileHealth: 1,
        projectileSpeed: 10,
    },
    {
        id: 2,
        image: loadImage("images/player/player2.png"),
        frontShots: 1,
        sideShots: 1,
        bounceCount: 0,
        width: 64,
        height: 64,
        maxHealth: 300,
        maxArmor: 300,
        armorRegen: 50,
        movementSpeed: 5,
        originShootingCooldown: 13,
        projectileDamage: 50,
        projectileHealth: 1,
        projectileSpeed: 11,
    },
    {
        id: 3,
        image: loadImage("images/player/player3.png"),
        frontShots: 2,
        sideShots: 1,
        bounceCount: 1,
        width: 64,
        height: 64,
        maxHealth: 600,
        maxArmor: 600,
        armorRegen: 100,
        movementSpeed: 7,
        originShootingCooldown: 10,
        projectileDamage: 80,
        projectileHealth: 2,
        projectileSpeed: 12,
    },
    {
        id: 4,
        image: loadImage("images/player/player4.png"),
        frontShots: 3,
        sideShots: 2,
        bounceCount: 2,
        width: 64,
        height: 128,
        maxHealth: 2000,
        maxArmor: 2000,
        armorRegen: 300,
        movementSpeed: 9,
        originShootingCooldown: 8,
        projectileDamage: 150,
        projectileHealth: 3,
        projectileSpeed: 13,
    },
];

//Powrup information
const powerups = [
    {
        name: "Laser",
        id: "lsr",
        req: 1, //Player ship level required to use
        duration: 60,
    },
    {
        name: "Explosive",
        id: "exp",
        req: 1,
        duration: 500,
    },
    {
        name: "Swords",
        id: "swd",
        req: 2,
        duration: 500,
        count: 3,
    },
    {
        name: "Barrier",
        id: "bar",
        req: 2,
        duration: 2000,
    },
    {
        name: "Scatter",
        id: "sca",
        req: 3,
    },
    {
        name: "Invincibility",
        id: "inv",
        req: 3,
        duration: 300,
    },
    {
        name: "Triple Shot",
        id: "tri",
        req: 4,
        duration: 300,
    },
    {
        name: "Boost",
        id: "bst",
        req: 4,
        duration: 300,
    },
];

//Information about upgrades
const upgrades = [
    {
        name: "Damage",
        id: "dmg",
        maxStacks: 10,
        weight: 3,
        multiplier: 1.5,
    },
    {
        name: "Attack Speed",
        id: "spd",
        maxStacks: 10,
        weight: 3,
    },
    {
        name: "Armor",
        id: "arm",
        maxStacks: 10,
        weight: 3,
        multiplier: 1.5,
    },
    {
        name: "Front Shots",
        id: "frt",
        maxStacks: 5,
        weight: 1.5,
        multiplier: 1.1,
    },
    {
        name: "Side Shots",
        id: "sid",
        maxStacks: 5,
        weight: 1.5,
        multiplier: 1.1,
    },
    {
        name: "Bounce Count + Pierce",
        id: "bou",
        maxStacks: 5,
        weight: 1,
    },
    {
        name: "Score Multiplier + Streak Allowed Time",
        id: "sco",
        maxStacks: 5,
        weight: 2,
        multiplier: 1.2,
    },
    {
        name: "Exp gain",
        id: "exp",
        maxStacks: 5,
        weight: 2,
        multiplier: 1.2,
    },
];

//Abilities for enemies
const abilities = [
    {
        name: "shield",
        compatible: 1, //Minimum tier required to use
    },
    {
        name: "berserk",
        compatible: 1,
    },
    {
        name: "preserve",
        compatible: 3,
    },
    {
        name: "revive",
        compatible: 3,
    },
    {
        name: "heal",
        compatible: 2,
    },
];

//Information on all enemies
const enemyTypes = [
    {
        id: "tank01",
        type: "melee",
        maxHealth: 50,
        weight: 2.75,
        xSpeed: 4,
        ySpeed: 1,
        width: 50,
        height: 50,
        image: null,
        point: 10,
        power: 2,
        movement: ["straight", "sine", "hold", "bounce"],
    },
    {
        id: "tank02",
        type: "melee",
        maxHealth: 200,
        weight: 2.5,
        xSpeed: 3,
        ySpeed: 2,
        width: 64,
        height: 64,
        image: null,
        point: 30,
        power: 5,
        movement: ["straight", "sine", "zigzag", "hold", "bounce", "semiHoming"],
    },
    {
        id: "tank03",
        type: "melee",
        maxHealth: 500,
        weight: 2.5,
        xSpeed: 7,
        ySpeed: 5,
        width: 75,
        height: 75,
        image: null,
        point: 70,
        power: 25,
        movement: ["loop", "hold", "bounce", "zigzag", "spread", "random"],
    },
    {
        id: "tank04",
        type: "melee",
        maxHealth: 5000,
        weight: 1.25,
        xSpeed: 10,
        ySpeed: 5,
        width: 100,
        height: 100,
        image: null,
        point: 100,
        power: 50,
        movement: ["spread", "hold", "loop", "random"],
    },
    {
        id: "charge01",
        type: "melee",
        maxHealth: 20,
        weight: 3.5,
        xSpeed: 3,
        ySpeed: 4,
        width: 50,
        height: 50,
        image: null,
        point: 5,
        power: 1,
        movement: ["straight", "jitter", "accel", "zigzag", "semiHoming", "charge"],
    },
    {
        id: "charge02",
        type: "melee",
        maxHealth: 50,
        weight: 2,
        xSpeed: 4,
        ySpeed: 5,
        width: 45,
        height: 45,
        image: null,
        point: 20,
        power: 3,
        movement: ["random", "accel", "zigzag", "semiHoming", "charge"],
    },
    {
        id: "charge03",
        type: "melee",
        maxHealth: 200,
        weight: 1.5,
        xSpeed: 8,
        ySpeed: 7,
        width: 40,
        height: 40,
        image: null,
        point: 50,
        power: 35,
        movement: ["random", "accel", "randomZigzag", "trueHoming", "superCharge", "spreadHoming"],
    },
    {
        id: "charge04",
        type: "melee",
        maxHealth: 500,
        weight: 1,
        xSpeed: 10,
        ySpeed: 8,
        width: 35,
        height: 35,
        image: null,
        point: 70,
        power: 60,
        movement: ["spreadHoming", "random", "randomZigzag", "trueHoming", "hyperCharge"],
    },
    {
        id: "shoot01",
        type: "range",
        maxHealth: 20,
        weight: 3.5,
        xSpeed: 3,
        ySpeed: 4,
        width: 50,
        height: 50,
        image: null,
        point: 15,
        track: false,
        bulletSpeed: 3,
        shotDelay: 80,
        damage: 5,
        power: 3,
        bulletTypes: ["normal"],
        shooting: ["straight1"],
        movement: ["loop", "hold", "retreat"],
    },
    {
        id: "shoot02",
        type: "range",
        maxHealth: 50,
        weight: 2,
        xSpeed: 5,
        ySpeed: 4,
        width: 50,
        height: 50,
        image: null,
        point: 40,
        track: false,
        bulletSpeed: 3.5,
        shotDelay: 60,
        damage: 10,
        power: 8,
        bulletTypes: ["normal", "homing"],
        shooting: ["side1"],
        movement: ["loop", "hold", "retreat"],
    },
    {
        id: "shoot03",
        type: "range",
        maxHealth: 200,
        weight: 1.5,
        xSpeed: 7,
        ySpeed: 4,
        width: 50,
        height: 50,
        image: null,
        point: 100,
        track: false,
        bulletSpeed: 4,
        shotDelay: 40,
        damage: 20,
        power: 40,
        bulletTypes: ["normal", "bounce"],
        shooting: ["straight1", "side1"],
        movement: ["loop", "hold", "retreat", "semiMirror"],
    },
    {
        id: "shoot04",
        type: "range",
        maxHealth: 500,
        weight: 1,
        xSpeed: 9,
        ySpeed: 4,
        width: 50,
        height: 50,
        image: null,
        point: 150,
        track: false,
        bulletSpeed: 4.5,
        shotDelay: 30,
        damage: 50,
        power: 70,
        bulletTypes: ["normal", "bounce"],
        shooting: ["straight2", "side2"],
        movement: ["loop", "hold", "trueMirror"],
    },
    {
        id: "snipe01",
        type: "range",
        maxHealth: 20,
        weight: 3.5,
        xSpeed: 3,
        ySpeed: 4,
        width: 50,
        height: 50,
        image: null,
        point: 15,
        track: true,
        bulletSpeed: 5,
        shotDelay: 150,
        damage: 10,
        power: 4,
        bulletTypes: ["normal", "bounce", "homing"],
        shooting: ["straight1"],
        movement: ["loop", "hold", "retreat"],
    },
    {
        id: "snipe02",
        type: "range",
        maxHealth: 50,
        weight: 2,
        xSpeed: 5,
        ySpeed: 4,
        width: 50,
        height: 50,
        image: null,
        point: 40,
        track: true,
        bulletSpeed: 5.5,
        shotDelay: 120,
        damage: 20,
        power: 15,
        bulletTypes: ["normal", "bounce", "homing"],
        shooting: ["side1"],
        movement: ["loop", "hold", "retreat"],
    },
    {
        id: "snipe03",
        type: "range",
        maxHealth: 200,
        weight: 1.5,
        xSpeed: 7,
        ySpeed: 4,
        width: 50,
        height: 50,
        image: null,
        point: 100,
        track: true,
        bulletSpeed: 6,
        shotDelay: 70,
        damage: 50,
        power: 50,
        bulletTypes: ["normal", "bounce"],
        shooting: ["straight1", "multi"],
        movement: ["loop", "hold", "retreat", "semiMirror"],
    },
    {
        id: "snipe04",
        type: "range",
        maxHealth: 500,
        weight: 1,
        xSpeed: 9,
        ySpeed: 4,
        width: 50,
        height: 50,
        image: null,
        point: 150,
        track: true,
        bulletSpeed: 7,
        shotDelay: 60,
        damage: 200,
        power: 70,
        bulletTypes: ["normal", "bounce"],
        shooting: ["straight1", "side1", "multi"],
        movement: ["loop", "hold", "trueMirror"],
    },
];

//Constants for streak count display and upgrade message display
const streakDisplayTime = 300,
    upgradeDisplayTime = 300,
    streakFadeSpeed = 0.02,
    upgradeFadeSpeed = 0.02;

// Starfield settings
const starCount = 100,
    starSpeed = 0.3;
